"""工具函数模块"""

from .exceptions import (
    APIError,
    BadRequestError,
    ValidationError,
    AuthenticationError,
    PermissionError,
    NotFoundError,
    RateLimitError,
    RequestTooLargeError,
    InternalError,
    ServiceUnavailableError,
    GatewayTimeoutError,
    ModelNotFoundError,
    ContextLengthExceededError,
    ToolCallError,
    StreamError,
    ContinuationError,
    UpstreamError,
    create_error_response,
)

from .logging import (
    setup_logging,
    get_logger,
    get_request_id,
    set_request_id,
    generate_request_id,
    get_request_duration,
    metrics,
    MetricsCollector,
    log_function_call,
)

from .json_parser import (
    safe_json_loads,
    try_parse_json,
    repair_json,
    extract_json_object,
    find_json_end,
    merge_json_objects,
    truncate_json_string,
)

from .tool_parser import (
    ParsedToolCall,
    ToolParseResult,
    parse_tool_calls,
    parse_inline_tool_calls,
    parse_xml_tool_calls,
    format_tool_call_inline,
    format_tool_call_xml,
    has_tool_call_marker,
    has_incomplete_tool_call,
    extract_text_before_tools,
    extract_text_after_tools,
    generate_tool_id,
)

__all__ = [
    # Exceptions
    "APIError",
    "BadRequestError",
    "ValidationError",
    "AuthenticationError",
    "PermissionError",
    "NotFoundError",
    "RateLimitError",
    "RequestTooLargeError",
    "InternalError",
    "ServiceUnavailableError",
    "GatewayTimeoutError",
    "ModelNotFoundError",
    "ContextLengthExceededError",
    "ToolCallError",
    "StreamError",
    "ContinuationError",
    "UpstreamError",
    "create_error_response",
    # Logging
    "setup_logging",
    "get_logger",
    "get_request_id",
    "set_request_id",
    "generate_request_id",
    "get_request_duration",
    "metrics",
    "MetricsCollector",
    "log_function_call",
    # JSON
    "safe_json_loads",
    "try_parse_json",
    "repair_json",
    "extract_json_object",
    "find_json_end",
    "merge_json_objects",
    "truncate_json_string",
    # Tool Parser
    "ParsedToolCall",
    "ToolParseResult",
    "parse_tool_calls",
    "parse_inline_tool_calls",
    "parse_xml_tool_calls",
    "format_tool_call_inline",
    "format_tool_call_xml",
    "has_tool_call_marker",
    "has_incomplete_tool_call",
    "extract_text_before_tools",
    "extract_text_after_tools",
    "generate_tool_id",
]
